# Generated by Django 3.1.8 on 2021-04-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
